name: Auto Pull Main Branch

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  auto-pull:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Windows server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd C:\binance_trade_copier
          git fetch origin main
          git reset --hard origin/main
          echo "✅ Successfully pulled latest changes to server"
          taskkill /F /IM python.exe 2>nul || echo "No Python process to kill"
          timeout /t 2 /nobreak >nul
          powershell -Command "Start-Process python -ArgumentList 'main.py' -WindowStyle Hidden"
          
          echo "✅ Server restarted successfully"
    
    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd C:\binance_trade_copier
          for /f %%i in ('git rev-parse HEAD') do echo Current commit: %%i
          
          rem Check if Python process is running
          tasklist /FI "IMAGENAME eq python.exe" 2>nul | find /I "python.exe" >nul
          if %ERRORLEVEL% equ 0 (
            echo "✅ Server is running"
          ) else (
            echo "❌ Server is not running"
            exit /b 1
          )
