name: Test SSH Connection

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "✅ SSH connection successful!"
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"
          echo "Server hostname: $(hostname)"
          echo "Home directory: $HOME"
          echo "Available disk space:"
          df -h
          
    - name: Test Git Access
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          if [ -d "/binance_trade_copier" ]; then
            cd /binance_trade_copier
            echo "✅ Project directory exists"
            echo "Current branch: $(git branch --show-current)"
            echo "Git status:"
            git status --porcelain
          else
            echo "❌ Project directory /binance_trade_copier not found"
            echo "Available directories in root:"
            ls -la /
            exit 1
          fi
          
    - name: Test Deployment Commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /binance_trade_copier
          echo "Testing git fetch..."
          git fetch origin main
          echo "✅ Git fetch successful"
          
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Remote commit: $(git rev-parse origin/main)"
          
          echo "Testing process detection..."
          if pgrep -f "python.*main.py" > /dev/null; then
            echo "✅ Python process detected"
          else
            echo "ℹ️ No Python process currently running"
          fi
          
          echo "✅ All deployment commands tested successfully"
